### ISSUE TITLE
Query string arguments cause BadRouteError

### ISSUE THREAD

**Issue by blakerobertson** [NathanRSmith/http-rendezvous#7]
The regex's used to match routes are stricter than necessary, sometimes causing unexpected behavior for clients. For example, one of our http clients sends an auth-related argument in the query string of every request it makes because it's needed 90% of the time, and unknown query string arguments are normally ignored by routers.

How to Reproduce:
Send a valid request to any route with any query string at the end of the URL.

What Happens:
The server returns `BadRouteError: No endpoint exists for the specified method and/or route`.

What's Expected:
The request executes as normal, ignoring the query string.

**Comment by NathanRSmith** [comment]
I agree, we should only look at the url path, not the query string.
